# Generated by Django 4.1.3 on 2022-11-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhutapp', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
